export const USER_SIGNIN = 'USER_SIGNIN'
export const USER_SIGNOUT = 'USER_LOGOUT'

export const SELECT_COMPANY = 'SELECT_COMPANY'
export const DESELECT_COMPANY = 'DESELECT_COMPANY'
export const SUGGEST_COMPANIES = 'SUGGEST_COMPANIES'

export const REPORT_CREATE_REQUEST = 'REPORT_CREATE_REQUEST'
export const REPORT_CREATE_SUCCESS = 'REPORT_CREATE_SUCCESS'
export const REPORT_CREATE_FAIL = 'REPORT_CREATE_FAIL'

export const SHOW_INFO_SNACKBAR = 'SHOW_INFO_SNACKBAR'
export const SHOW_STATIC_INFO_SNACKBAR = 'SHOW_STATIC_INFO_SNACKBAR'
export const SHOW_SUCCESS_SNACKBAR = 'SHOW_SUCCESS_SNACKBAR'
export const SHOW_WARNING_SNACKBAR = 'SHOW_WARNING_SNACKBAR'
export const SHOW_ERROR_SNACKBAR = 'SHOW_ERROR_SNACKBAR'
export const DISMISS_SNACKBAR = 'DISMISS_SNACKBAR'

export const GRAPH_TOGGLE_RELATIVE = 'GRAPH_TOGGLE_RELATIVE'
