query getEventBeveragesConsumption($id: ID!) {
  Event(id: $id) {
    menuBeverages {
      id
      beverage {
        id
        name
      }
      consumptions {
        consumedAt
      }
    }
  }
}
