#import '../fragments/beverageInfo.gql'
#import '../fragments/eventInfo.gql'

query getEvents($filter: EventFilter) {
  allEvents(filter: $filter, orderBy: finishAt_DESC) {
    ...eventInfo
    menuBeverages {
      id
      ...beverageInfo
      consumptions {
        consumedAt
      }
    }
  }
}
